
redis:
  host: localhost
  port: 6379
  key:
    chat-room : "chat:room:"
    room : "chat:room:"
    message : "chat:message:"
    session : "connected:"
    user : "connected:user"


kafka:
  bootstrapServer: localhost:9092
  topic :
    chat : chat
